# Site wide configuration

title: gi
header: gi
locale: en_US
description: 
logo: j.jpg
search: false
url: http://giuliatomasello.github.io

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: gi
  avatar: j.jpg
  email: tomasello.gi@gmail.com
  disqus-shortname:
  twitter: gitomasello
  instagram: gitomasello
  tumblr: giuliatomasello
  pinterest: gitomasello
  vimeo: gitomasello
  flickr: giuliatomasello
  github: giuliatomasello
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: giuliatomasello
  google:
    plus: Giuliatomasellogi
    analytics:
    verify:
    ad-client:
    ad-slot: 
  bing-verify:
  markdown: redcarpet
